
# slrparse.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'SLR'

_lr_signature = 'EQ ID TIMES\n    s : l EQ r\n      | r\n    \n    l : TIMES r\n      | ID\n    \n    r : l\n    '
    
_lr_action_items = {'TIMES':([0,4,6,],[4,4,4,]),'ID':([0,4,6,],[5,5,5,]),'$end':([1,2,3,5,7,8,9,],[0,-5,-2,-4,-3,-5,-1,]),'EQ':([2,5,7,8,],[6,-4,-3,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'s':([0,],[1,]),'l':([0,4,6,],[2,8,8,]),'r':([0,4,6,],[3,7,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> s","S'",1,None,None,None),
  ('s -> l EQ r','s',3,'p_s','slrvslalr.py',14),
  ('s -> r','s',1,'p_s','slrvslalr.py',15),
  ('l -> TIMES r','l',2,'p_l','slrvslalr.py',20),
  ('l -> ID','l',1,'p_l','slrvslalr.py',21),
  ('r -> l','r',1,'p_r','slrvslalr.py',26),
]
